version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: npm
    versions:
    - 6.14.11
    - 7.5.1
    - 7.5.2
    - 7.5.3
    - 7.5.4
    - 7.5.6
    - 7.6.0
    - 7.6.1
    - 7.6.2
    - 7.6.3
    - 7.7.0
    - 7.7.2
    - 7.7.4
    - 7.7.5
    - 7.7.6
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: react-json-view
    versions:
    - 1.20.4
    - 1.20.5
    - 1.21.0
    - 1.21.1
    - 1.21.2
    - 1.21.3
  - dependency-name: highcharts
    versions:
    - 9.0.0
  - dependency-name: bootswatch
    versions:
    - 4.6.0
  - dependency-name: reactstrap
    versions:
    - 8.9.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
- package-ecosystem: terraform
  directory: "/deploy"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nginx
    versions:
    - 1.19.6.pre.alpine
    - 1.19.7.pre.alpine
    - 1.19.8.pre.alpine
  - dependency-name: node
    versions:
    - 15.10.0
    - 15.11.0
    - 15.7.0
    - 15.8.0
    - 15.9.0
